drop schema if exists `dw` ;

-- CREATE SCHEMA DW 

CREATE SCHEMA `dw` ;
USE `dw` ;

-- CREATE TABLE CUSTOMER 

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID VARCHAR(4), 
    CUSTOMER_NAME VARCHAR(30) not null,
    CONSTRAINT `CUSTOMERS_PK` PRIMARY KEY (CUSTOMER_ID)
) ;

-- CREATE TABLE PRODUCTS 
  
CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR(6), 
	PRODUCT_NAME VARCHAR(30) NOT NULL, 
    PRICE DOUBLE(5,2) DEFAULT 0.0,
    CONSTRAINT `PRODUCTS_PK` PRIMARY KEY (PRODUCT_ID)
    );
    
-- CREATE TABLE STORE

CREATE TABLE STORE(
	STORE_ID VARCHAR(4) , 
	STORE_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT `STORE_PK` PRIMARY KEY (STORE_ID)
    );
    
-- CREATE TABLE SUPPLIER    

CREATE TABLE SUPPLIER(
	SUPPLIER_ID VARCHAR(5), 
	SUPPLIER_NAME VARCHAR(30) NOT NULL, 
	CONSTRAINT `SUPPLIER_PK` PRIMARY KEY (SUPPLIER_ID)
    );

-- CREATE TABLE TIME

CREATE TABLE TIME(
	TIME_ID VARCHAR(8), 
	T_DATE DATE NOT NULL,
    T_DAY varchar(20) NOT NULL,
    T_MONTH INT NOT NULL,
    T_YEAR INT NOT NULL,
	CONSTRAINT `TIME_PK` PRIMARY KEY (TIME_ID)
);


-- CREATE TABLE TRANSACTION

CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID DOUBLE(8,0), 
	PRODUCT_ID VARCHAR(6) NOT NULL, 
	CUSTOMER_ID VARCHAR(4) NOT NULL, 
	STORE_ID VARCHAR(4) NOT NULL, 
	SUPPLIER_ID VARCHAR(5) NOT NULL,
	TIME_ID VARCHAR(8) NOT NULL,
	QUANTITY DOUBLE(3,0) NOT NULL,
    SALE DOUBLE(3,0) NOT NULL,
	CONSTRAINT `TRANSACTION_PK` PRIMARY KEY (TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,STORE_ID,SUPPLIER_ID,TIME_ID)

    
    );



ALTER TABLE `dw`.`transactions` 
ADD INDEX `CUSTOMER_FK_idx` (`CUSTOMER_ID` ASC) VISIBLE,
ADD INDEX `PRODUCT_FK_idx` (`PRODUCT_ID` ASC) VISIBLE,
ADD INDEX `STORE_FK_idx` (`STORE_ID` ASC) VISIBLE,
ADD INDEX `SUPPLIER_FK_idx` (`SUPPLIER_ID` ASC) VISIBLE,
ADD INDEX `TIME_FK_idx` (`TIME_ID` ASC) VISIBLE;
;
ALTER TABLE `dw`.`transactions` 
ADD CONSTRAINT `CUSTOMER_FK`
  FOREIGN KEY (`CUSTOMER_ID`)
  REFERENCES `dw`.`customers` (`CUSTOMER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `PRODUCT_FK`
  FOREIGN KEY (`PRODUCT_ID`)
  REFERENCES `dw`.`products` (`PRODUCT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `STORE_FK`
  FOREIGN KEY (`STORE_ID`)
  REFERENCES `dw`.`store` (`STORE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SUPPLIER_FK`
  FOREIGN KEY (`SUPPLIER_ID`)
  REFERENCES `dw`.`supplier` (`SUPPLIER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `TIME_FK`
  FOREIGN KEY (`TIME_ID`)
  REFERENCES `dw`.`time` (`TIME_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


	

	
  