-- __________________QUERY 1 _____________________

SELECT STORE_NAME , sum(SALE) as Count FROM DW.TRANSACTIONS T 
		 JOIN STORE S 
         ON T.STORE_ID = S.STORE_ID
         JOIN TIME TM ON T.TIME_ID = TM.TIME_ID 
         WHERE MONTH(T_DATE) = 9 AND YEAR(T_DATE) = 2017
         GROUP BY STORE_NAME 
         ORDER BY Count DESC 
         LIMIT 3;
         
-- __________________QUERY 2 _____________________

SELECT T.SUPPLIER_ID,SUPPLIER_NAME,SUM(SALE) as TOTAL , count(*) AS COUNT FROM TRANSACTIONS T
		JOIN SUPPLIER S 
        ON T.SUPPLIER_ID = S.SUPPLIER_ID
        JOIN TIME TM
        ON T.TIME_ID = TM.TIME_ID
        WHERE T_DAY IN ('Saturday' , 'Sunday')
        GROUP BY T.SUPPLIER_ID
        ORDER BY TOTAL DESC
        LIMIT 10;


-- __________________QUERY 3 _____________________


SELECT SUPPLIER_NAME,MONTHNAME(T_DATE) AS "MONTH",T_MONTH, QUARTER(T_DATE) AS "QUARTER", SUM(SALE) AS "SALE"
		FROM TRANSACTIONS T 
		JOIN PRODUCTS P
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN SUPPLIER S
        ON T.SUPPLIER_ID = S.SUPPLIER_ID
        JOIN TIME TM
        ON T.TIME_ID = TM.TIME_ID
        GROUP BY T.SUPPLIER_ID , QUARTER , MONTH WITH ROLLUP
        ORDER BY SUPPLIER_NAME,T_MONTH ASC;
        
        
-- __________________QUERY 4 _____________________


SELECT STORE_NAME,PRODUCT_NAME , SUM(SALE) AS SALE FROM TRANSACTIONS T
		JOIN PRODUCTS P 
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN STORE S
        ON T.STORE_ID = S.STORE_ID
        GROUP BY STORE_NAME,PRODUCT_NAME WITH ROLLUP;


-- __________________QUERY 5 _____________________

SELECT T.STORE_ID,STORE_NAME,QUARTER(T_DATE) AS "QUARTER", SUM(SALE) AS SALE FROM TRANSACTIONS T
		JOIN STORE S
        ON T.STORE_ID = S.STORE_ID
        JOIN TIME TM
        ON T.TIME_ID = TM.TIME_ID
        GROUP BY T.STORE_ID,QUARTER 
        ORDER BY T.STORE_ID,QUARTER
        ;



-- __________________QUERY 6 _____________________

SELECT T.PRODUCT_ID,PRODUCT_NAME,COUNT(*) AS "TOTAL" FROM DW.TRANSACTIONS T 
		 JOIN PRODUCTS P 
         ON T.PRODUCT_ID = P.PRODUCT_ID
         JOIN TIME TM ON T.TIME_ID = TM.TIME_ID 
         WHERE DAYNAME(T_DATE) IN ('Saturday' , 'Sunday')
         GROUP BY T.PRODUCT_ID,PRODUCT_NAME 
         ORDER BY TOTAL DESC 
         LIMIT 5;
         
-- __________________QUERY 7 _____________________

SELECT STORE_NAME,SUPPLIER_NAME,PRODUCT_NAME ,SUM(SALE) AS TOTAL FROM TRANSACTIONS T
		JOIN STORE S
        ON T.STORE_ID = S.STORE_ID
        JOIN PRODUCTS P
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN SUPPLIER SP
        ON T.SUPPLIER_ID = SP.SUPPLIER_ID
        GROUP BY STORE_NAME,SUPPLIER_NAME,PRODUCT_NAME WITH ROLLUP;
        
        
        
-- __________________QUERY 8 _____________________

SELECT T.PRODUCT_ID,PRODUCT_NAME ,SUM(SALE) AS SALE , T_DATE FROM TRANSACTIONS T
		JOIN TIME TM
        ON T.TIME_ID = TM.TIME_ID
        JOIN PRODUCTS P 
        ON T.PRODUCT_ID = P.PRODUCT_ID
        WHERE YEAR(T_DATE) = 2017 AND MONTH(T_DATE) BETWEEN '01' AND '06' 
        GROUP BY T.PRODUCT_ID 
UNION

SELECT T.PRODUCT_ID,PRODUCT_NAME ,SUM(SALE) AS SALE , T_DATE FROM TRANSACTIONS T
		JOIN TIME TM
        ON T.TIME_ID = TM.TIME_ID
        JOIN PRODUCTS P 
        ON T.PRODUCT_ID = P.PRODUCT_ID
        WHERE YEAR(T_DATE) = 2017 AND MONTH(T_DATE) BETWEEN '07' AND '12' 
        GROUP BY T.PRODUCT_ID 
        ORDER BY T_DATE asc;
        
        

-- __________________QUERY 9 _____________________


SELECT T.PRODUCT_ID, PRODUCT_NAME,T.SUPPLIER_ID,SUPPLIER_NAME FROM TRANSACTIONS T
		JOIN PRODUCTS P 
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN SUPPLIER S
        ON T.SUPPLIER_ID = S.SUPPLIER_ID
        WHERE PRODUCT_NAME = "Tomatoes";
        
        
SELECT * FROM STORE 
		GROUP BY STORE_NAME
        HAVING COUNT(STORE_NAME) > 1;
        
SELECT * FROM SUPPLIER 
		GROUP BY SUPPLIER_NAME
        HAVING COUNT(SUPPLIER_NAME) > 1;
        
        
SELECT * FROM PRODUCTS 
		GROUP BY PRODUCT_NAME
        HAVING COUNT(PRODUCT_NAME) > 1;

SELECT * FROM PRODUCTS WHERE PRODUCT_NAME = "Tomatoes";



-- __________________QUERY 10 _____________________

	CREATE VIEW STORE_PRODUCT_ANALYSIS AS
    SELECT STORE_NAME , PRODUCT_NAME , SUM(SALE) AS SALES
    FROM TRANSACTIONS T
    JOIN STORE S
	ON T.STORE_ID = S.STORE_ID 
    JOIN PRODUCTS P 
    ON T.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY STORE_NAME,PRODUCT_NAME WITH ROLLUP;
    
    SELECT * FROM STORE_PRODUCT_ANALYSIS;
    
    DROP VIEW STORE_PRODUCT_ANALYSIS;
